branch-defaults:
  master:
    environment: roda-test-dev
    group_suffix: null
global:
  application_name: roda-test
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.2 (Puma)
  default_region: us-east-1
  profile: eb-cli
  sc: git
